export interface Sp500UniverseEntry {
  symbol: string;
  sector: string;
  industry: string;
}

/** Top S&P 500 constituents by market cap — used for the home heatmap treemap. */
export const SP500_HEATMAP_UNIVERSE: Sp500UniverseEntry[] = [
  { symbol: "AAPL", sector: "Technology", industry: "Consumer Electronics" },
  { symbol: "MSFT", sector: "Technology", industry: "Software — Infrastructure" },
  { symbol: "NVDA", sector: "Technology", industry: "Semiconductors" },
  { symbol: "AVGO", sector: "Technology", industry: "Semiconductors" },
  { symbol: "ORCL", sector: "Technology", industry: "Software — Infrastructure" },
  { symbol: "CRM", sector: "Technology", industry: "Software — Application" },
  { symbol: "ADBE", sector: "Technology", industry: "Software — Infrastructure" },
  { symbol: "AMD", sector: "Technology", industry: "Semiconductors" },
  { symbol: "INTC", sector: "Technology", industry: "Semiconductors" },
  { symbol: "CSCO", sector: "Technology", industry: "Communication Equipment" },
  { symbol: "ACN", sector: "Technology", industry: "IT Services" },
  { symbol: "IBM", sector: "Technology", industry: "IT Services" },
  { symbol: "TXN", sector: "Technology", industry: "Semiconductors" },
  { symbol: "QCOM", sector: "Technology", industry: "Semiconductors" },
  { symbol: "AMAT", sector: "Technology", industry: "Semiconductors" },
  { symbol: "INTU", sector: "Technology", industry: "Software — Application" },
  { symbol: "NOW", sector: "Technology", industry: "Software — Application" },
  { symbol: "PANW", sector: "Technology", industry: "Software — Infrastructure" },
  { symbol: "MU", sector: "Technology", industry: "Semiconductors" },
  { symbol: "LRCX", sector: "Technology", industry: "Semiconductors" },
  { symbol: "KLAC", sector: "Technology", industry: "Semiconductors" },
  { symbol: "ADI", sector: "Technology", industry: "Semiconductors" },
  { symbol: "SNPS", sector: "Technology", industry: "Software — Application" },
  { symbol: "CDNS", sector: "Technology", industry: "Software — Application" },
  { symbol: "CRWD", sector: "Technology", industry: "Software — Infrastructure" },
  { symbol: "GOOGL", sector: "Communication Services", industry: "Internet Content" },
  { symbol: "META", sector: "Communication Services", industry: "Internet Content" },
  { symbol: "NFLX", sector: "Communication Services", industry: "Entertainment" },
  { symbol: "DIS", sector: "Communication Services", industry: "Entertainment" },
  { symbol: "VZ", sector: "Communication Services", industry: "Telecom Services" },
  { symbol: "CMCSA", sector: "Communication Services", industry: "Telecom Services" },
  { symbol: "T", sector: "Communication Services", industry: "Telecom Services" },
  { symbol: "TMUS", sector: "Communication Services", industry: "Telecom Services" },
  { symbol: "AMZN", sector: "Consumer Cyclical", industry: "Internet Retail" },
  { symbol: "TSLA", sector: "Consumer Cyclical", industry: "Auto Manufacturers" },
  { symbol: "HD", sector: "Consumer Cyclical", industry: "Home Improvement" },
  { symbol: "MCD", sector: "Consumer Cyclical", industry: "Restaurants" },
  { symbol: "NKE", sector: "Consumer Cyclical", industry: "Apparel Manufacturing" },
  { symbol: "LOW", sector: "Consumer Cyclical", industry: "Home Improvement" },
  { symbol: "SBUX", sector: "Consumer Cyclical", industry: "Restaurants" },
  { symbol: "TJX", sector: "Consumer Cyclical", industry: "Apparel Retail" },
  { symbol: "BKNG", sector: "Consumer Cyclical", industry: "Travel Services" },
  { symbol: "MAR", sector: "Consumer Cyclical", industry: "Lodging" },
  { symbol: "UNH", sector: "Healthcare", industry: "Healthcare Plans" },
  { symbol: "LLY", sector: "Healthcare", industry: "Drug Manufacturers" },
  { symbol: "JNJ", sector: "Healthcare", industry: "Drug Manufacturers" },
  { symbol: "ABBV", sector: "Healthcare", industry: "Drug Manufacturers" },
  { symbol: "MRK", sector: "Healthcare", industry: "Drug Manufacturers" },
  { symbol: "TMO", sector: "Healthcare", industry: "Diagnostics & Research" },
  { symbol: "ABT", sector: "Healthcare", industry: "Medical Devices" },
  { symbol: "PFE", sector: "Healthcare", industry: "Drug Manufacturers" },
  { symbol: "ISRG", sector: "Healthcare", industry: "Medical Devices" },
  { symbol: "SYK", sector: "Healthcare", industry: "Medical Devices" },
  { symbol: "DHR", sector: "Healthcare", industry: "Diagnostics & Research" },
  { symbol: "BMY", sector: "Healthcare", industry: "Drug Manufacturers" },
  { symbol: "GILD", sector: "Healthcare", industry: "Drug Manufacturers" },
  { symbol: "VRTX", sector: "Healthcare", industry: "Biotechnology" },
  { symbol: "CI", sector: "Healthcare", industry: "Healthcare Plans" },
  { symbol: "BRK-B", sector: "Financial", industry: "Insurance — Diversified" },
  { symbol: "JPM", sector: "Financial", industry: "Banks — Diversified" },
  { symbol: "V", sector: "Financial", industry: "Credit Services" },
  { symbol: "MA", sector: "Financial", industry: "Credit Services" },
  { symbol: "BAC", sector: "Financial", industry: "Banks — Diversified" },
  { symbol: "GS", sector: "Financial", industry: "Capital Markets" },
  { symbol: "MS", sector: "Financial", industry: "Capital Markets" },
  { symbol: "WFC", sector: "Financial", industry: "Banks — Diversified" },
  { symbol: "C", sector: "Financial", industry: "Banks — Diversified" },
  { symbol: "SCHW", sector: "Financial", industry: "Capital Markets" },
  { symbol: "BLK", sector: "Financial", industry: "Asset Management" },
  { symbol: "SPGI", sector: "Financial", industry: "Financial Data" },
  { symbol: "AXP", sector: "Financial", industry: "Credit Services" },
  { symbol: "CB", sector: "Financial", industry: "Insurance — Property" },
  { symbol: "PGR", sector: "Financial", industry: "Insurance — Property" },
  { symbol: "CME", sector: "Financial", industry: "Financial Exchanges" },
  { symbol: "GE", sector: "Industrials", industry: "Specialty Industrial" },
  { symbol: "CAT", sector: "Industrials", industry: "Farm & Heavy Equipment" },
  { symbol: "HON", sector: "Industrials", industry: "Conglomerates" },
  { symbol: "RTX", sector: "Industrials", industry: "Aerospace & Defense" },
  { symbol: "UNP", sector: "Industrials", industry: "Railroads" },
  { symbol: "DE", sector: "Industrials", industry: "Farm & Heavy Equipment" },
  { symbol: "UPS", sector: "Industrials", industry: "Integrated Freight" },
  { symbol: "BA", sector: "Industrials", industry: "Aerospace & Defense" },
  { symbol: "LMT", sector: "Industrials", industry: "Aerospace & Defense" },
  { symbol: "ADP", sector: "Industrials", industry: "Staffing & Employment" },
  { symbol: "PG", sector: "Consumer Defensive", industry: "Household & Personal" },
  { symbol: "COST", sector: "Consumer Defensive", industry: "Discount Stores" },
  { symbol: "KO", sector: "Consumer Defensive", industry: "Beverages — Non-Alcoholic" },
  { symbol: "PEP", sector: "Consumer Defensive", industry: "Beverages — Non-Alcoholic" },
  { symbol: "WMT", sector: "Consumer Defensive", industry: "Discount Stores" },
  { symbol: "PM", sector: "Consumer Defensive", industry: "Tobacco" },
  { symbol: "MDLZ", sector: "Consumer Defensive", industry: "Confectioners" },
  { symbol: "CL", sector: "Consumer Defensive", industry: "Household & Personal" },
  { symbol: "MO", sector: "Consumer Defensive", industry: "Tobacco" },
  { symbol: "KHC", sector: "Consumer Defensive", industry: "Packaged Foods" },
  { symbol: "XOM", sector: "Energy", industry: "Oil & Gas Integrated" },
  { symbol: "CVX", sector: "Energy", industry: "Oil & Gas Integrated" },
  { symbol: "COP", sector: "Energy", industry: "Oil & Gas E&P" },
  { symbol: "SLB", sector: "Energy", industry: "Oil & Gas Services" },
  { symbol: "EOG", sector: "Energy", industry: "Oil & Gas E&P" },
  { symbol: "MPC", sector: "Energy", industry: "Oil & Gas Refining" },
  { symbol: "NEE", sector: "Utilities", industry: "Utilities — Regulated Electric" },
  { symbol: "DUK", sector: "Utilities", industry: "Utilities — Regulated Electric" },
  { symbol: "SO", sector: "Utilities", industry: "Utilities — Regulated Electric" },
  { symbol: "AEP", sector: "Utilities", industry: "Utilities — Regulated Electric" },
  { symbol: "AMT", sector: "Real Estate", industry: "REIT — Specialty" },
  { symbol: "PLD", sector: "Real Estate", industry: "REIT — Industrial" },
  { symbol: "EQIX", sector: "Real Estate", industry: "REIT — Specialty" },
  { symbol: "SPG", sector: "Real Estate", industry: "REIT — Retail" },
  { symbol: "LIN", sector: "Basic Materials", industry: "Specialty Chemicals" },
  { symbol: "SHW", sector: "Basic Materials", industry: "Specialty Chemicals" },
  { symbol: "FCX", sector: "Basic Materials", industry: "Copper" },
  { symbol: "NEM", sector: "Basic Materials", industry: "Gold" },
  { symbol: "ECL", sector: "Basic Materials", industry: "Specialty Chemicals" },
  { symbol: "APD", sector: "Basic Materials", industry: "Specialty Chemicals" },
];

export const SP500_HEATMAP_SYMBOLS = SP500_HEATMAP_UNIVERSE.map(
  (entry) => entry.symbol,
) as readonly string[];

const METADATA = new Map(
  SP500_HEATMAP_UNIVERSE.map((entry) => [entry.symbol, entry]),
);

export function getStockMetadata(symbol: string): {
  sector: string;
  industry: string;
} {
  const entry = METADATA.get(symbol);
  return entry
    ? { sector: entry.sector, industry: entry.industry }
    : { sector: "Other", industry: "Diversified" };
}
