/**
 * Curated peer seeds keyed by Yahoo `industryKey` / `sectorKey`.
 * Used for granular peer-relative scoring when live industry screeners are unavailable.
 * Prefer industryKey (sub-industry); sectorKey is fallback only.
 */

export const INDUSTRY_PEER_SEEDS: Record<string, string[]> = {
  // Capital markets / brokerage / exchanges
  "capital-markets": [
    "HOOD",
    "SCHW",
    "IBKR",
    "RJF",
    "LPLA",
    "MS",
    "GS",
    "AMP",
    "SF",
    "VIRT",
  ],
  "financial-data-stock-exchanges": [
    "ICE",
    "CME",
    "NDAQ",
    "CBOE",
    "SPGI",
    "MCO",
    "MSCI",
    "FDS",
  ],
  "asset-management": [
    "BLK",
    "BX",
    "KKR",
    "APO",
    "TROW",
    "BEN",
    "IVZ",
    "AMG",
  ],
  "credit-services": [
    "V",
    "MA",
    "AXP",
    "COF",
    "DFS",
    "SYF",
    "SOFI",
    "UPST",
  ],
  "banks-diversified": [
    "JPM",
    "BAC",
    "WFC",
    "C",
    "USB",
    "PNC",
    "TFC",
    "BK",
  ],
  "banks-regional": [
    "CFG",
    "KEY",
    "RF",
    "HBAN",
    "MTB",
    "FITB",
    "ZION",
    "CMA",
  ],
  "insurance-diversified": ["BRK-B", "AIG", "MET", "PRU", "AFL", "HIG"],
  "insurance-property-casualty": ["PGR", "TRV", "ALL", "CB", "ACGL", "WRB"],
  "insurance-life": ["MET", "PRU", "LNC", "VOYA", "GL", "PFG"],

  // Technology
  "consumer-electronics": [
    "AAPL",
    "SONY",
    "DELL",
    "HPQ",
    "LOGI",
    "GPRO",
    "XIACF",
    "PCRFY",
    "HEAR",
    "SONO",
  ],
  "computer-hardware": [
    "AAPL",
    "DELL",
    "HPQ",
    "SMCI",
    "ANET",
    "NTAP",
    "WDC",
    "STX",
  ],
  "communication-equipment": [
    "CSCO",
    "ANET",
    "UI",
    "JNPR",
    "ERIC",
    "NOK",
    "CIEN",
  ],
  "software-infrastructure": [
    "MSFT",
    "ORCL",
    "CRM",
    "NOW",
    "SNOW",
    "DDOG",
    "NET",
    "CRWD",
    "ZS",
    "PLTR",
  ],
  "software-application": [
    "ADBE",
    "INTU",
    "WDAY",
    "TEAM",
    "SHOP",
    "HUBS",
    "DOCU",
    "ZM",
  ],
  "semiconductors": [
    "NVDA",
    "AMD",
    "AVGO",
    "QCOM",
    "TXN",
    "INTC",
    "MU",
    "AMAT",
    "LRCX",
    "KLAC",
  ],
  "semiconductor-equipment-materials": ["ASML", "AMAT", "LRCX", "KLAC", "TER"],
  "information-technology-services": [
    "ACN",
    "IBM",
    "CTSH",
    "IT",
    "EPAM",
    "INFY",
  ],
  "internet-content-information": [
    "GOOGL",
    "META",
    "SNAP",
    "PINS",
    "RDDT",
    "MTCH",
  ],
  "electronic-gaming-multimedia": ["EA", "TTWO", "RBLX", "U", "NTES"],

  // Healthcare
  "biotechnology": [
    "VRTX",
    "REGN",
    "GILD",
    "BIIB",
    "MRNA",
    "BNTX",
    "ALNY",
    "INCY",
  ],
  "drug-manufacturers-general": [
    "JNJ",
    "PFE",
    "MRK",
    "ABBV",
    "LLY",
    "BMY",
    "AZN",
    "NVO",
  ],
  "drug-manufacturers-specialty-generic": ["TEVA", "VTRS", "CTL", "PRGO"],
  "medical-devices": ["MDT", "ABT", "SYK", "BSX", "EW", "ZBH", "DXCM"],
  "health-information-services": ["VEEV", "GEHC", "TDOC", "OMCL"],
  "healthcare-plans": ["UNH", "ELV", "CVS", "CI", "HUM", "CNC", "MOH"],

  // Consumer
  "beverages-non-alcoholic": ["KO", "PEP", "MNST", "KDP", "CELH"],
  "beverages-brewers": ["BUD", "STZ", "TAP", "SAM"],
  "restaurants": ["MCD", "SBUX", "CMG", "YUM", "DPZ", "QSR", "WING"],
  "apparel-retail": ["NKE", "LULU", "TJX", "ROST", "GPS", "ANF", "URBN"],
  "internet-retail": ["AMZN", "BABA", "MELI", "ETSY", "W", "CHWY"],
  "auto-manufacturers": ["TSLA", "F", "GM", "TM", "HMC", "RIVN", "LCID"],
  "footwear-accessories": ["NKE", "DECK", "CROX", "SKX", "ONON"],
  "household-personal-products": ["PG", "CL", "KMB", "CHD", "EL", "CLX"],
  "packaged-foods": ["GIS", "K", "CPB", "CAG", "HRL", "SJM", "MKC"],
  "tobacco": ["PM", "MO", "BTI", "UVV"],

  // Energy / materials / industrials
  "oil-gas-integrated": ["XOM", "CVX", "SHEL", "TTE", "BP"],
  "oil-gas-ep": ["COP", "EOG", "PXD", "DVN", "FANG", "OXY", "HES"],
  "oil-gas-midstream": ["EPD", "ET", "WMB", "KMI", "OKE", "MPLX"],
  "specialty-industrial-machinery": ["ETN", "EMR", "ROK", "PH", "ITW", "IR"],
  "aerospace-defense": ["BA", "LMT", "RTX", "NOC", "GD", "HII", "LHX"],
  "farm-heavy-construction-machinery": ["CAT", "DE", "PCAR", "CMI", "AGCO"],

  // Real estate / utilities / infra
  "reit-specialty": ["AMT", "CCI", "EQIX", "DLR", "SBAC", "IRM"],
  "reit-industrial": ["PLD", "REX", "EGP", "FR", "TRNO"],
  "reit-retail": ["SPG", "O", "REG", "KIM", "FRT"],
  "reit-residential": ["AVB", "EQR", "ESS", "MAA", "UDR", "CPT"],
  "utilities-regulated-electric": [
    "NEE",
    "DUK",
    "SO",
    "D",
    "AEP",
    "EXC",
    "SRE",
    "XEL",
  ],
  "utilities-renewable": ["NEE", "AES", "BEP", "CWEN", "RUN", "ENPH", "FLNC"],
  "utilities-diversified": ["SRE", "PEG", "ED", "EIX", "WEC"],
};

/** Broad sector fallback seeds — used only when industry peers are too sparse. */
export const SECTOR_PEER_SEEDS: Record<string, string[]> = {
  "financial-services": [
    "JPM",
    "BAC",
    "GS",
    "MS",
    "SCHW",
    "BLK",
    "V",
    "MA",
    "AXP",
    "SPGI",
  ],
  technology: [
    "AAPL",
    "MSFT",
    "NVDA",
    "AVGO",
    "ORCL",
    "CRM",
    "AMD",
    "ADBE",
    "CSCO",
    "ACN",
  ],
  healthcare: [
    "UNH",
    "LLY",
    "JNJ",
    "ABBV",
    "MRK",
    "TMO",
    "ABT",
    "PFE",
    "AMGN",
    "ISRG",
  ],
  "consumer-cyclical": [
    "AMZN",
    "TSLA",
    "HD",
    "MCD",
    "NKE",
    "SBUX",
    "LOW",
    "BKNG",
    "TJX",
    "CMG",
  ],
  "consumer-defensive": [
    "WMT",
    "PG",
    "KO",
    "PEP",
    "COST",
    "PM",
    "MO",
    "CL",
    "MDLZ",
    "KHC",
  ],
  "communication-services": [
    "GOOGL",
    "META",
    "NFLX",
    "DIS",
    "CMCSA",
    "T",
    "VZ",
    "TMUS",
    "EA",
    "TTWO",
  ],
  energy: ["XOM", "CVX", "COP", "SLB", "EOG", "MPC", "PSX", "VLO", "WMB", "OKE"],
  industrials: [
    "GE",
    "CAT",
    "UNP",
    "HON",
    "UPS",
    "RTX",
    "BA",
    "DE",
    "LMT",
    "ETN",
  ],
  "basic-materials": [
    "LIN",
    "APD",
    "SHW",
    "ECL",
    "FCX",
    "NEM",
    "NUE",
    "DOW",
    "DD",
    "ALB",
  ],
  "real-estate": [
    "PLD",
    "AMT",
    "EQIX",
    "SPG",
    "PSA",
    "O",
    "CCI",
    "DLR",
    "WELL",
    "AVB",
  ],
  utilities: ["NEE", "SO", "DUK", "SRE", "AEP", "D", "EXC", "XEL", "PEG", "ED"],
};

/** Map closely related industryKeys into a shared industry-group fallback. */
export const INDUSTRY_GROUP_ALIASES: Record<string, string[]> = {
  "capital-markets": [
    "capital-markets",
    "financial-data-stock-exchanges",
    "asset-management",
  ],
  "financial-data-stock-exchanges": [
    "financial-data-stock-exchanges",
    "capital-markets",
    "asset-management",
  ],
  "asset-management": [
    "asset-management",
    "capital-markets",
    "financial-data-stock-exchanges",
  ],
  "banks-diversified": ["banks-diversified", "banks-regional"],
  "banks-regional": ["banks-regional", "banks-diversified"],
  "auto-manufacturers": [
    "auto-manufacturers",
    "auto-parts",
    "auto-recreational-vehicles",
  ],
  "consumer-electronics": [
    "consumer-electronics",
    "computer-hardware",
    "communication-equipment",
  ],
  "computer-hardware": [
    "computer-hardware",
    "consumer-electronics",
    "communication-equipment",
  ],
  "communication-equipment": [
    "communication-equipment",
    "computer-hardware",
    "consumer-electronics",
  ],
  "software-infrastructure": [
    "software-infrastructure",
    "software-application",
  ],
  "software-application": ["software-application", "software-infrastructure"],
  semiconductors: ["semiconductors", "semiconductor-equipment-materials"],
  "semiconductor-equipment-materials": [
    "semiconductor-equipment-materials",
    "semiconductors",
  ],
  biotechnology: ["biotechnology", "drug-manufacturers-general"],
  "reit-specialty": [
    "reit-specialty",
    "reit-industrial",
    "reit-retail",
    "reit-residential",
  ],
  "utilities-regulated-electric": [
    "utilities-regulated-electric",
    "utilities-diversified",
    "utilities-renewable",
  ],
};

export const MIN_PEER_COUNT = 3;
/** Cap peer fan-out hard — each peer is 1 ratios-ttm call. */
export const MAX_PEERS_FETCH = 5;
/** Accept a thinner set from the first seed tier before cascading. */
export const ACCEPT_PEER_COUNT = 3;
